name: API Tests

on:
  push:
    branches: [ main ]  # Run the tests on every push to the main branch
  pull_request:
    branches: [ main ]  # Run the tests on every pull request targeting the main branch

jobs:
  test:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements file for your dependencies

      - name: Run tests
        run: python -m unittest discover -s tests -p "test_*.py"  # Adjust the path and pattern based on your test file names and structure
